// ============================================================
// Popular character tags + approximate post counts on rule34.xxx
// Counts are snapshots (not live). Update periodically if desired.
// ============================================================

const CHARACTERS = [
  { name: "2B", tag: "2b_(nier)", count: 185000 },
  { name: "Asuka Langley", tag: "souryuu_asuka_langley", count: 92000 },
  { name: "Hatsune Miku", tag: "hatsune_miku", count: 210000 },
  { name: "Rem", tag: "rem_(re:zero)", count: 78000 },
  { name: "Zero Two", tag: "zero_two_(darling_in_the_franxx)", count: 95000 },
  { name: "Chun-Li", tag: "chun-li", count: 68000 },
  { name: "Tifa Lockhart", tag: "tifa_lockhart", count: 72000 },
  { name: "Samus Aran", tag: "samus_aran", count: 55000 },
  { name: "Marisa Kirisame", tag: "kirisame_marisa", count: 48000 },
  { name: "Reimu Hakurei", tag: "hakurei_reimu", count: 52000 },
  { name: "Hinata Hyuga", tag: "hyuuga_hinata", count: 41000 },
  { name: "Sakura Haruno", tag: "haruno_sakura", count: 38000 },
  { name: "Nezuko Kamado", tag: "kamado_nezuko", count: 45000 },
  { name: "Mikasa Ackerman", tag: "mikasa_ackerman", count: 32000 },
  { name: "Annie Leonhart", tag: "annie_leonhart", count: 18000 },
  { name: "Power", tag: "power_(chainsaw_man)", count: 28000 },
  { name: "Makima", tag: "makima_(chainsaw_man)", count: 35000 },
  { name: "Yor Forger", tag: "yor_briar", count: 22000 },
  { name: "Anya Forger", tag: "anya_forger", count: 15000 },
  { name: "Frieren", tag: "frieren", count: 19000 },
  { name: "Fern", tag: "fern_(sousou_no_frieren)", count: 12000 },
  { name: "Aqua", tag: "aqua_(konosuba)", count: 34000 },
  { name: "Megumin", tag: "megumin", count: 42000 },
  { name: "Darkness", tag: "darkness_(konosuba)", count: 25000 },
  { name: "Emilia", tag: "emilia_(re:zero)", count: 31000 },
  { name: "Ram", tag: "ram_(re:zero)", count: 24000 },
  { name: "Beatrice", tag: "beatrice_(re:zero)", count: 16000 },
  { name: "Raphtalia", tag: "raphtalia", count: 27000 },
  { name: "Filo", tag: "filo_(tate_no_yuusha)", count: 14000 },
  { name: "Naofumi", tag: "iwatani_naofumi", count: 9000 },
  { name: "Widowmaker", tag: "widowmaker", count: 48000 },
  { name: "Tracer", tag: "tracer", count: 36000 },
  { name: "D.Va", tag: "d.va_(overwatch)", count: 52000 },
  { name: "Mercy", tag: "mercy", count: 29000 },
  { name: "Jinx", tag: "jinx_(league_of_legends)", count: 41000 },
  { name: "Ahri", tag: "ahri", count: 58000 },
  { name: "Lux", tag: "lux", count: 22000 },
  { name: "Miss Fortune", tag: "miss_fortune", count: 19000 },
  { name: "Cammy", tag: "cammy", count: 31000 },
  { name: "Mai Shiranui", tag: "mai_shiranui", count: 44000 },
  { name: "Princess Peach", tag: "princess_peach", count: 38000 },
  { name: "Rosalina", tag: "rosalina", count: 21000 },
  { name: "Zelda", tag: "princess_zelda", count: 33000 },
  { name: "Link", tag: "link", count: 28000 },
  { name: "Ganondorf", tag: "ganondorf", count: 8000 },
  { name: "Bayonetta", tag: "bayonetta", count: 24000 },
  { name: "Ciri", tag: "cirilla_fiona_elen_rianon", count: 17000 },
  { name: "Yennefer", tag: "yennefer", count: 15000 },
  { name: "Triss", tag: "triss_merigold", count: 12000 },
  { name: "Geralt", tag: "geralt_of_rivia", count: 9000 },
  { name: "Lara Croft", tag: "lara_croft", count: 26000 },
  { name: "Ada Wong", tag: "ada_wong", count: 23000 },
  { name: "Jill Valentine", tag: "jill_valentine", count: 18000 },
  { name: "Quiet", tag: "quiet_(metal_gear)", count: 14000 },
  { name: "Cortana", tag: "cortana", count: 11000 },
  { name: "Aloy", tag: "aloy", count: 8000 },
  { name: "Ellie", tag: "ellie_(the_last_of_us)", count: 13000 },
  { name: "Abby", tag: "abby_(the_last_of_us)", count: 7000 },
  { name: "A2", tag: "a2_(nier)", count: 22000 },
  { name: "Asuna", tag: "asuna_(sao)", count: 36000 },
  { name: "Sinon", tag: "sinon", count: 19000 },
  { name: "Kirito", tag: "kirito", count: 14000 },
  { name: "Erza Scarlet", tag: "erza_scarlet", count: 28000 },
  { name: "Lucy Heartfilia", tag: "lucy_heartfilia", count: 21000 },
  { name: "Nami", tag: "nami_(one_piece)", count: 45000 },
  { name: "Nico Robin", tag: "nico_robin", count: 32000 },
  { name: "Boa Hancock", tag: "boa_hancock", count: 27000 },
  { name: "Bulma", tag: "bulma", count: 24000 },
  { name: "Android 18", tag: "android_18", count: 29000 },
  { name: "Rias Gremory", tag: "rias_gremory", count: 31000 },
  { name: "Akeno", tag: "himejima_akeno", count: 26000 },
  { name: "Hestia", tag: "hestia_(danmachi)", count: 23000 },
  { name: "Bell Cranel", tag: "bell_cranel", count: 6000 },
  { name: "Albedo", tag: "albedo_(overlord)", count: 28000 },
  { name: "Shalltear", tag: "shalltear_bloodfallen", count: 18000 },
  { name: "Miku Nakano", tag: "nakano_miku", count: 16000 },
  { name: "Nino Nakano", tag: "nakano_nino", count: 17000 },
  { name: "Itsuki Nakano", tag: "nakano_itsuki", count: 11000 },
  { name: "Rukia", tag: "kuchiki_rukia", count: 15000 },
  { name: "Orihime", tag: "inoue_orihime", count: 12000 },
  { name: "Yoruichi", tag: "shihouin_yoruichi", count: 14000 },
  { name: "Kaguya Shinomiya", tag: "shinomiya_kaguya", count: 13000 },
  { name: "Chika Fujiwara", tag: "fujiwara_chika", count: 10000 },
  { name: "Mai Sakurajima", tag: "sakurajima_mai", count: 25000 },
  { name: "Rio Futaba", tag: "futaba_rio", count: 8000 },
  { name: "Komi Shouko", tag: "komi_shouko", count: 14000 },
  { name: "Nagatoro", tag: "nagatoro", count: 19000 },
  { name: "Raiden Shogun", tag: "raiden_shogun", count: 48000 },
  { name: "Yae Miko", tag: "yae_miko", count: 42000 },
  { name: "Ganyu", tag: "ganyu_(genshin_impact)", count: 51000 },
  { name: "Hu Tao", tag: "hu_tao_(genshin_impact)", count: 39000 },
  { name: "Zhongli", tag: "zhongli_(genshin_impact)", count: 16000 },
  { name: "Venti", tag: "venti_(genshin_impact)", count: 18000 },
  { name: "Keqing", tag: "keqing_(genshin_impact)", count: 28000 },
  { name: "Jean", tag: "jean_(genshin_impact)", count: 15000 },
  { name: "Barbara", tag: "barbara_(genshin_impact)", count: 14000 },
  { name: "Fischl", tag: "fischl_(genshin_impact)", count: 17000 },
  { name: "Nahida", tag: "nahida_(genshin_impact)", count: 22000 },
  { name: "Furina", tag: "furina_(genshin_impact)", count: 26000 },
  { name: "Navia", tag: "navia_(genshin_impact)", count: 11000 },
  { name: "Clorinde", tag: "clorinde_(genshin_impact)", count: 9000 },
  { name: "Arlecchino", tag: "arlecchino_(genshin_impact)", count: 13000 },
  { name: "Shenhe", tag: "shenhe_(genshin_impact)", count: 16000 },
  { name: "Eula", tag: "eula_(genshin_impact)", count: 19000 },
  { name: "Ayaka", tag: "kamisato_ayaka", count: 24000 },
  { name: "Ayato", tag: "kamisato_ayato", count: 7000 },
  { name: "Yoimiya", tag: "yoimiya_(genshin_impact)", count: 12000 },
  { name: "Sonic", tag: "sonic_the_hedgehog", count: 22000 },
  { name: "Amy Rose", tag: "amy_rose", count: 18000 },
  { name: "Rouge the Bat", tag: "rouge_the_bat", count: 15000 },
  { name: "Blaze", tag: "blaze_the_cat", count: 8000 },
  { name: "Isabelle", tag: "isabelle_(animal_crossing)", count: 12000 },
  { name: "Pikachu", tag: "pikachu", count: 35000 },
  { name: "Gardevoir", tag: "gardevoir", count: 28000 },
  { name: "Lucario", tag: "lucario", count: 16000 },
  { name: "Mewtwo", tag: "mewtwo", count: 9000 },
  { name: "Umbreon", tag: "umbreon", count: 11000 },
  { name: "Eevee", tag: "eevee", count: 14000 },
  { name: "Lopunny", tag: "lopunny", count: 13000 },
  { name: "Vaporeon", tag: "vaporeon", count: 17000 },
  { name: "Charizard", tag: "charizard", count: 12000 },
  { name: "Gengar", tag: "gengar", count: 8000 },
  { name: "Snorlax", tag: "snorlax", count: 5000 },
  { name: "Jigglypuff", tag: "jigglypuff", count: 7000 },
  { name: "Mimikyu", tag: "mimikyu", count: 9000 },
];

const VALID_CHARACTERS = CHARACTERS.filter(c => c.count > 0 && c.name && c.tag);
